# -*- coding: iso-8859-1 -*-

# Form implementation generated from reading ui file 'forms/altitude_dialog.ui'
#
# Created: Fri Jun 29 18:56:15 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_altitude_Dialog(object):
    def setupUi(self, altitude_Dialog):
        altitude_Dialog.setObjectName(_fromUtf8("altitude_Dialog"))
        altitude_Dialog.resize(392, 251)
        self.verticalLayout = QtGui.QVBoxLayout(altitude_Dialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtGui.QLabel(altitude_Dialog)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.wiki_url_label = QtGui.QLabel(altitude_Dialog)
        self.wiki_url_label.setObjectName(_fromUtf8("wiki_url_label"))
        self.verticalLayout.addWidget(self.wiki_url_label)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_2 = QtGui.QLabel(altitude_Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(60, 0))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout.addWidget(self.label_2)
        self.latitude_doubleSpinBox = QtGui.QDoubleSpinBox(altitude_Dialog)
        self.latitude_doubleSpinBox.setMinimumSize(QtCore.QSize(120, 0))
        self.latitude_doubleSpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.latitude_doubleSpinBox.setDecimals(5)
        self.latitude_doubleSpinBox.setMinimum(-90.0)
        self.latitude_doubleSpinBox.setMaximum(90.0)
        self.latitude_doubleSpinBox.setSingleStep(0.01)
        self.latitude_doubleSpinBox.setObjectName(_fromUtf8("latitude_doubleSpinBox"))
        self.horizontalLayout.addWidget(self.latitude_doubleSpinBox)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_3 = QtGui.QLabel(altitude_Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(60, 0))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_2.addWidget(self.label_3)
        self.altitude_doubleSpinBox = QtGui.QDoubleSpinBox(altitude_Dialog)
        self.altitude_doubleSpinBox.setMinimumSize(QtCore.QSize(120, 0))
        self.altitude_doubleSpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.altitude_doubleSpinBox.setMinimum(-10000.0)
        self.altitude_doubleSpinBox.setMaximum(10000.0)
        self.altitude_doubleSpinBox.setSingleStep(0.2)
        self.altitude_doubleSpinBox.setObjectName(_fromUtf8("altitude_doubleSpinBox"))
        self.horizontalLayout_2.addWidget(self.altitude_doubleSpinBox)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_5 = QtGui.QLabel(altitude_Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(60, 0))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_4.addWidget(self.label_5)
        self.g_label = QtGui.QLabel(altitude_Dialog)
        self.g_label.setMinimumSize(QtCore.QSize(120, 0))
        self.g_label.setFrameShape(QtGui.QFrame.StyledPanel)
        self.g_label.setFrameShadow(QtGui.QFrame.Sunken)
        self.g_label.setLineWidth(1)
        self.g_label.setMidLineWidth(0)
        self.g_label.setAlignment(QtCore.Qt.AlignCenter)
        self.g_label.setObjectName(_fromUtf8("g_label"))
        self.horizontalLayout_4.addWidget(self.g_label)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.label_4 = QtGui.QLabel(altitude_Dialog)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout.addWidget(self.label_4)
        self.gmap_label = QtGui.QLabel(altitude_Dialog)
        self.gmap_label.setObjectName(_fromUtf8("gmap_label"))
        self.verticalLayout.addWidget(self.gmap_label)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.ok_pushButton = QtGui.QPushButton(altitude_Dialog)
        self.ok_pushButton.setObjectName(_fromUtf8("ok_pushButton"))
        self.horizontalLayout_3.addWidget(self.ok_pushButton)
        self.cancel_pushButton = QtGui.QPushButton(altitude_Dialog)
        self.cancel_pushButton.setObjectName(_fromUtf8("cancel_pushButton"))
        self.horizontalLayout_3.addWidget(self.cancel_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(altitude_Dialog)
        QtCore.QObject.connect(self.ok_pushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), altitude_Dialog.accept)
        QtCore.QObject.connect(self.cancel_pushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), altitude_Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(altitude_Dialog)

    def retranslateUi(self, altitude_Dialog):
        altitude_Dialog.setWindowTitle(QtGui.QApplication.translate("altitude_Dialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("altitude_Dialog", "A latitude e a altitude serão utilizados para calcular a \n"
"aceleração da gravidade em sua região, segunda\n"
"a expressão em:", None, QtGui.QApplication.UnicodeUTF8))
        self.wiki_url_label.setText(QtGui.QApplication.translate("altitude_Dialog", "<a href=\"http://pt.wikipedia.org/wiki/Aceleração_da_gravidade\">http://pt.wikipedia.org/wiki/Aceleração_da_gravidade</a>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("altitude_Dialog", "Latitude:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("altitude_Dialog", "Altitude:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("altitude_Dialog", "Aceleração da Gravidade (m/s²):", None, QtGui.QApplication.UnicodeUTF8))
        self.g_label.setText(QtGui.QApplication.translate("altitude_Dialog", "9,80", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("altitude_Dialog", "Sua latitude e altitude podem ser obtida de páginas\n"
"como o:", None, QtGui.QApplication.UnicodeUTF8))
        self.gmap_label.setText(QtGui.QApplication.translate("altitude_Dialog", "<a href=\"http://www.gorissen.info/Pierre/maps/googleMapLocation.php\">googleMapLocation</a>", None, QtGui.QApplication.UnicodeUTF8))
        self.ok_pushButton.setText(QtGui.QApplication.translate("altitude_Dialog", "&Ok", None, QtGui.QApplication.UnicodeUTF8))
        self.cancel_pushButton.setText(QtGui.QApplication.translate("altitude_Dialog", "&Cancela", None, QtGui.QApplication.UnicodeUTF8))

